# src/main/resources/application.yml
server:
  port: 8080

spring:
  profiles:
    active:
    - dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Configuration for Actuator endpoints
  main:
    allow-bean-definition-overriding: true # Allows overriding beans if defined in profiles

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env,metrics,mappings,httptrace,loggers # From Lab 7

# Custom Application Properties
app:
  message:  Welcome to the Product API (NOT DEV/TEST)!
  api-version: 1.0.0